#!/bin/bash

echo "Genius : " >> GeniusTests.txt
echo "DRIBBLE 5 FOLD : " >> GeniusTests.txt
./dectree -d ../Genius/dats/dribbleFile.dat 5 6150 >> GeniusTests.txt
echo " " >> GeniusTests.txt
echo "PASS 5 FOLD : " >> GeniusTests.txt 
./dectree -p ../Genius/dats/passFile.dat 5 4900 >> GeniusTests.txt
echo " " >> GeniusTests.txt
echo "SHOOT 5 FOLD : " >> GeniusTests.txt 
./dectree -s ../Genius/dats/shotFile.dat 5 820 >> GeniusTests.txt
echo " " >> GeniusTests.txt

echo "Helios : " >> HeliosTests.txt
echo "DRIBBLE 5 FOLD : " >> HeliosTests.txt
./dectree -d ../Helios/dats/dribbleFile.dat 5 6100 >> HeliosTests.txt
echo " " >> HeliosTests.txt
echo "PASS 5 FOLD : " >> HeliosTests.txt 
./dectree -p ../Helios/dats/passFile.dat 5 5010 >> HeliosTests.txt
echo " " >> HeliosTests.txt
echo "SHOOT 5 FOLD : " >> HeliosTests.txt 
./dectree -s ../Helios/dats/shotFile.dat 5 870 >> HeliosTests.txt

echo "Hermes : " >> HermesTests.txt
echo "DRIBBLE 5 FOLD : " >> HermesTests.txt
./dectree -d ../Hermes/dats/dribbleFile.dat 5 5860 >> HermesTests.txt
echo " " >> HermesTests.txt
echo "PASS 5 FOLD : " >> HermesTests.txt 
./dectree -p ../Hermes/dats/passFile.dat 5 5070 >> HermesTests.txt
echo " " >> HermesTests.txt
echo "SHOOT 5 FOLD : " >> HermesTests.txt 
./dectree -s ../Hermes/dats/shotFile.dat 5 780 >> HermesTests.txt

echo "Jaeger : " >> JaegerTests.txt
echo "DRIBBLE 5 FOLD : " >> JaegerTests.txt
./dectree -d ../Jaeger/dats/dribbleFile.dat 5 6440 >> JaegerTests.txt
echo " " >> JaegerTests.txt
echo "PASS 5 FOLD : " >> JaegerTests.txt 
./dectree -p ../Jaeger/dats/passFile.dat 5 4970 >> JaegerTests.txt
echo " " >> JaegerTests.txt
echo "SHOOT 5 FOLD : " >> JaegerTests.txt 
./dectree -s ../Jaeger/dats/shotFile.dat 5 950 >> JaegerTests.txt


echo "WrightEagle : " >> WrightEagleTests.txt
echo "DRIBBLE 5 FOLD : " >> WrightEagleTests.txt
./dectree -d ../WrightEagle/dats/dribbleFile.dat 5 6310 >> WrightEagleTests.txt
echo " " >> WrightEagleTests.txt
echo "PASS 5 FOLD : " >> WrightEagleTests.txt 
./dectree -p ../WrightEagle/dats/passFile.dat 5 5680 >> WrightEagleTests.txt
echo " " >> WrightEagleTests.txt
echo "SHOOT 5 FOLD : " >> WrightEagleTests.txt 
./dectree -s ../WrightEagle/dats/shotFile.dat 5 850 >> WrightEagleTests.txt
echo " " >> WrightEagleTests.txt