#!/bin/bash

TEAM=$1


python3 passChecking.py ./logs/$TEAM/dats/10-11/dribbleFile.dat 5 23 "dribbleSinCont.dat" $TEAM"Dribble10-111Elem"

python3 passChecking.py ./logs/$TEAM/dats/10-11/passFile.dat 5 23 "passSinCont.dat" $TEAM"Pass10-111Elem"

python3 passChecking.py ./logs/$TEAM/dats/10-11/shotFile.dat 5 23 "shotSinCont.dat" $TEAM"Shot10-111Elem" 

rm $TEAM*10-111Elem

mv *SinCont.dat ./logs/$TEAM/dats/10-11/




