#!/bin/bash

# Para correrlo, primero meter este script en la carpeta de cada equipo excepto el nuestro
# (la carpeta donde esta el start.sh o startAll o como se llame)
# Cambiar el 20 en el while por cuantos partidos querramos hacer.

# En la carpeta del equipo contra el que vamos a jugar, correr :
# ./autoplay 'path absoluto al start.sh de JEMV en src' 'path absoluto al start del equipo contra el que vamos a jugar'
# (las comillas SI van)

# Ejemplo : 
# Estando parado en la carpeta de Jaeger (donde esta su start.sh), en mi computadora lo correria asi :
# ./autoplay '/home/jemd/Documents/USB/Tesis/robocup-coach/agent2d-3.1.1/src/start.sh' '/home/jemd/Documents/USB/Tesis/Teams/Jaeger/start.sh'
# y listo :D

TEAM_L=$1
TEAM_R=$2

count=0
while [ $count -lt 10 ]
do
  cp ../logs/$TEAM_R/dats/OnlyJEMV/Normalizados/*.dat ../agent2d-3.1.1/src/
  cp ../logs/$TEAM_R/dats/OnlyJEMV/Normalizados/*.yml ../agent2d-3.1.1/src/trainedTrees/$TEAM_R/
  count=$((count + 1))
  rcssserver server::auto_mode=on \
    server::team_l_start=$TEAM_L server::team_r_start=$TEAM_R \
    server::kick_off_wait=50 \
    server::synch_mode=on
  cp ../../robocup-coach/agent2d-3.1.1/src/baseEnemyFormations/* ../../robocup-coach/agent2d-3.1.1/src/enemyFormations/
  sleep 6
done
